name = "gps-qp-builder"
pages_build_output_dir = "./dist"
compatibility_date = "2026-09-12"

[[d1_databases]]
binding = "DB"
database_name = "gps-qp-builder-db"
database_id = "87b8c2b2-24cf-4a6b-b8ea-d7e2c15cb9af"
