name = "gps-qp-builder"
main = "worker/index.js"
compatibility_date = "2026-09-12"

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "gps-qp-builder-db"
database_id = "87b8c2b2-24cf-4a6b-b8ea-d7e2c15cb9af"
