const COOKIE = "gps_session";
const SESSION_DAYS = 7;
const encoder = new TextEncoder();

function json(data, status=200, extra={}) {
  return new Response(JSON.stringify(data), { status, headers: { "content-type":"application/json; charset=utf-8", "cache-control":"no-store", ...extra } });
}
function now(){return Date.now();}
function id(){return crypto.randomUUID();}
function b64(bytes){let s="";bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
function unb64(s){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const bin=atob(s);return Uint8Array.from(bin,c=>c.charCodeAt(0));}
async function sha256(value){const d=await crypto.subtle.digest("SHA-256",encoder.encode(value));return b64(new Uint8Array(d));}
async function randomToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return b64(bytes);}
async function hashPassword(password,saltB64){const salt=saltB64?unb64(saltB64):crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey("raw",encoder.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:120000,hash:"SHA-256"},key,256);return `pbkdf2$120000$${b64(salt)}$${b64(new Uint8Array(bits))}`;}
async function verifyPassword(password,stored){const [scheme,it,salt,hash]=String(stored).split("$");if(scheme!=="pbkdf2")return false;const candidate=await hashPassword(password,salt);return candidate===stored;}
function cookie(token,maxAge=SESSION_DAYS*86400){return `${COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`;}
function clearCookie(){return `${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`;}
function getCookie(request,name){const raw=request.headers.get("Cookie")||"";for(const part of raw.split(";")){const [k,...v]=part.trim().split("=");if(k===name)return v.join("=");}return null;}
async function currentUser(request,env){const raw=getCookie(request,COOKIE);if(!raw)return null;const th=await sha256(raw);const row=await env.DB.prepare(`SELECT s.user_id,s.impersonator_id,s.expires_at,u.id,u.username,u.name,u.email,u.role,u.active,u.force_password_change FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?`).bind(th,now()).first();if(!row||!row.active)return null;const impersonator=row.impersonator_id?await env.DB.prepare(`SELECT id,username,name,role FROM users WHERE id=?`).bind(row.impersonator_id).first():null;return {id:row.id,username:row.username,name:row.name,email:row.email,role:row.role,forcePasswordChange:!!row.force_password_change,impersonator:impersonator||null};}
async function writeAudit(env,actor,action,target=null,acting=null,metadata={}){await env.DB.prepare(`INSERT INTO audit_logs(id,actor_user_id,acting_user_id,action,target_user_id,metadata_json,created_at) VALUES(?,?,?,?,?,?,?)`).bind(id(),actor,acting,action,target,JSON.stringify(metadata),now()).run();}
function safeUser(row){return {id:row.id,username:row.username,name:row.name,email:row.email,role:row.role,active:!!row.active,forcePasswordChange:!!row.force_password_change,createdAt:row.created_at};}
async function workspace(env,userId){const row=await env.DB.prepare(`SELECT data_json FROM workspaces WHERE user_id=?`).bind(userId).first();if(!row)return {current:null,drafts:[],templates:[],settings:{}};try{return JSON.parse(row.data_json)||{}}catch{return {}}}
async function saveWorkspace(env,userId,data){await env.DB.prepare(`INSERT INTO workspaces(user_id,data_json,updated_at) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET data_json=excluded.data_json,updated_at=excluded.updated_at`).bind(userId,JSON.stringify(data||{}),now()).run();}

async function login(request,env){const body=await request.json().catch(()=>({}));const username=String(body.username||"").trim();const password=String(body.password||"");if(!username||!password)return json({error:"Enter username and password."},400);const u=await env.DB.prepare(`SELECT * FROM users WHERE username=? COLLATE NOCASE`).bind(username).first();if(!u||!u.active||!(await verifyPassword(password,u.password_hash)))return json({error:"Invalid username or password."},401);const token=await randomToken();await env.DB.prepare(`INSERT INTO sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)`).bind(await sha256(token),u.id,now()+SESSION_DAYS*86400000,now()).run();await writeAudit(env,u.id,"login",u.id);return json({user:safeUser(u),workspace:await workspace(env,u.id)},200,{"Set-Cookie":cookie(token)});}
async function authMe(request,env){const u=await currentUser(request,env);if(!u)return json({error:"Not signed in."},401);return json({user:u,workspace:await workspace(env,u.id)});}
async function logout(request,env){const raw=getCookie(request,COOKIE);if(raw)await env.DB.prepare(`DELETE FROM sessions WHERE token_hash=?`).bind(await sha256(raw)).run();return json({ok:true},200,{"Set-Cookie":clearCookie()});}
async function accountPut(request,env,u){const b=await request.json().catch(()=>({}));const name=String(b.name||"").trim().slice(0,120);const username=String(b.username||"").trim().slice(0,60);const email=String(b.email||"").trim().slice(0,160);if(!name||!username)return json({error:"Name and username are required."},400);try{await env.DB.prepare(`UPDATE users SET name=?,username=?,email=?,updated_at=? WHERE id=?`).bind(name,username,email,now(),u.id).run();const fresh=await env.DB.prepare(`SELECT * FROM users WHERE id=?`).bind(u.id).first();return json({user:safeUser(fresh)})}catch(e){return json({error:"That username is already in use."},409)}}
async function passwordPut(request,env,u){const b=await request.json().catch(()=>({}));const current=String(b.currentPassword||"");const next=String(b.newPassword||"");if(next.length<8)return json({error:"New password must be at least 8 characters."},400);const row=await env.DB.prepare(`SELECT password_hash FROM users WHERE id=?`).bind(u.id).first();if(!row||!(await verifyPassword(current,row.password_hash)))return json({error:"Current password is incorrect."},401);await env.DB.prepare(`UPDATE users SET password_hash=?,force_password_change=0,updated_at=? WHERE id=?`).bind(await hashPassword(next),now(),u.id).run();await writeAudit(env,u.id,"change_password",u.id);return json({ok:true});}

async function adminUsersGet(env,u){if(u.role!=="admin")return json({error:"Admin access required."},403);const rows=await env.DB.prepare(`SELECT * FROM users ORDER BY role DESC,name COLLATE NOCASE,username COLLATE NOCASE`).all();return json({users:(rows.results||[]).map(safeUser)});}
async function adminUserCreate(request,env,u){if(u.role!=="admin")return json({error:"Admin access required."},403);const b=await request.json().catch(()=>({}));const name=String(b.name||"").trim();const username=String(b.username||"").trim();const email=String(b.email||"").trim();const password=String(b.password||"");if(!name||!username||password.length<8)return json({error:"Name, username and a password of at least 8 characters are required."},400);const uid=id();try{await env.DB.prepare(`INSERT INTO users(id,username,password_hash,name,email,role,active,force_password_change,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(uid,username,await hashPassword(password),name,email,"teacher",1,1,now(),now()).run();await saveWorkspace(env,uid,{current:null,drafts:[],templates:[],settings:{}});await writeAudit(env,u.id,"create_user",uid,null,{role:"teacher"});return json({ok:true,user:{id:uid,username,name,email,role:"teacher",active:true}})}catch(e){return json({error:"That username is already in use."},409)}}
async function adminUserPatch(request,env,u,targetId){if(u.role!=="admin")return json({error:"Admin access required."},403);const b=await request.json().catch(()=>({}));const target=await env.DB.prepare(`SELECT * FROM users WHERE id=?`).bind(targetId).first();if(!target)return json({error:"User not found."},404);if(target.id===u.id&&b.active===false)return json({error:"You cannot disable your own account."},400);if(typeof b.active!=="boolean")return json({error:"No valid change supplied."},400);await env.DB.prepare(`UPDATE users SET active=?,updated_at=? WHERE id=?`).bind(b.active?1:0,now(),targetId).run();if(!b.active)await env.DB.prepare(`DELETE FROM sessions WHERE user_id=?`).bind(targetId).run();await writeAudit(env,u.id,b.active?"enable_user":"disable_user",targetId);return json({ok:true});}
async function adminReset(request,env,u,targetId){if(u.role!=="admin")return json({error:"Admin access required."},403);const b=await request.json().catch(()=>({}));const password=String(b.password||"");if(password.length<8)return json({error:"Temporary password must be at least 8 characters."},400);const target=await env.DB.prepare(`SELECT * FROM users WHERE id=?`).bind(targetId).first();if(!target)return json({error:"User not found."},404);await env.DB.prepare(`UPDATE users SET password_hash=?,force_password_change=1,updated_at=? WHERE id=?`).bind(await hashPassword(password),now(),targetId).run();await env.DB.prepare(`DELETE FROM sessions WHERE user_id=?`).bind(targetId).run();await writeAudit(env,u.id,"reset_password",targetId);return json({ok:true});}
async function impersonate(env,u,targetId){if(u.role!=="admin")return json({error:"Admin access required."},403);const target=await env.DB.prepare(`SELECT * FROM users WHERE id=?`).bind(targetId).first();if(!target||!target.active)return json({error:"Active user not found."},404);const token=await randomToken();await env.DB.prepare(`INSERT INTO sessions(token_hash,user_id,impersonator_id,expires_at,created_at) VALUES(?,?,?,?,?)`).bind(await sha256(token),target.id,u.id,now()+2*3600000,now()).run();await writeAudit(env,u.id,"impersonate",target.id,u.id);return json({ok:true},200,{"Set-Cookie":cookie(token,7200)});}
async function stopImpersonation(request,env,u){if(!u.impersonator)return json({error:"No impersonation session."},400);const raw=getCookie(request,COOKIE);if(raw)await env.DB.prepare(`DELETE FROM sessions WHERE token_hash=?`).bind(await sha256(raw)).run();const token=await randomToken();await env.DB.prepare(`INSERT INTO sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)`).bind(await sha256(token),u.impersonator.id,now()+SESSION_DAYS*86400000,now()).run();await writeAudit(env,u.impersonator.id,"stop_impersonation",u.id,u.impersonator.id);return json({ok:true},200,{"Set-Cookie":cookie(token)});}

async function setupStatus(env){const row=await env.DB.prepare(`SELECT COUNT(*) AS c FROM users`).first();return json({needsSetup:Number(row?.c||0)===0});}
async function setupBootstrap(request,env){const key=env.GPS_SETUP_KEY;if(!key)return json({error:"Set GPS_SETUP_KEY in Cloudflare environment variables first."},500);const supplied=request.headers.get("x-setup-key")||"";if(supplied!==key)return json({error:"Invalid setup key."},403);const count=await env.DB.prepare(`SELECT COUNT(*) AS c FROM users`).first();if(Number(count?.c||0)>0)return json({error:"Setup has already been completed."},409);const uid=id();await env.DB.prepare(`INSERT INTO users(id,username,password_hash,name,email,role,active,force_password_change,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(uid,"masterdev",await hashPassword("masterdev"),"masterdev","","admin",1,0,now(),now()).run();await saveWorkspace(env,uid,{current:null,drafts:[],templates:[],settings:{}});return json({ok:true});}

export default { async fetch(request,env){try{const url=new URL(request.url);if(url.pathname.startsWith("/api/")){if(!env.DB)return json({error:"Database is not configured. Bind a Cloudflare D1 database as DB."},500);if(request.method==="GET"&&url.pathname==="/api/setup/status")return setupStatus(env);if(request.method==="POST"&&url.pathname==="/api/setup/bootstrap")return setupBootstrap(request,env);if(request.method==="POST"&&url.pathname==="/api/auth/login")return login(request,env);if(url.pathname==="/api/auth/me")return authMe(request,env);if(request.method==="POST"&&url.pathname==="/api/auth/logout")return logout(request,env);const u=await currentUser(request,env);if(!u)return json({error:"Please sign in."},401);if(request.method==="PUT"&&url.pathname==="/api/auth/account")return accountPut(request,env,u);if(request.method==="PUT"&&url.pathname==="/api/auth/password")return passwordPut(request,env,u);if(request.method==="GET"&&url.pathname==="/api/workspace")return json({workspace:await workspace(env,u.id)});if(request.method==="PUT"&&url.pathname==="/api/workspace"){const data=await request.json().catch(()=>({}));await saveWorkspace(env,u.id,data);return json({ok:true});}if(url.pathname==="/api/admin/users"&&request.method==="GET")return adminUsersGet(env,u);if(url.pathname==="/api/admin/users"&&request.method==="POST")return adminUserCreate(request,env,u);const m=url.pathname.match(/^\/api\/admin\/users\/([^/]+)(?:\/(reset-password|impersonate))?$/);if(m&&request.method==="PATCH"&&!m[2])return adminUserPatch(request,env,u,m[1]);if(m&&request.method==="POST"&&m[2]==="reset-password")return adminReset(request,env,u,m[1]);if(m&&request.method==="POST"&&m[2]==="impersonate")return impersonate(env,u,m[1]);if(request.method==="POST"&&url.pathname==="/api/admin/stop-impersonation")return stopImpersonation(request,env,u);return json({error:"Not found."},404);}return env.ASSETS.fetch(request);}catch(e){return json({error:e?.message||"Server error."},500);}}};
